apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-viz
# Hay que correr esto antes de empezar para que kustomize encuentre helm
# export helmCommand=/usr/local/bin/helm

helmCharts:
  - name: superset
    repo: https://apache.github.io/superset
    version: 0.7.4
    releaseName: superset-tf-release
    valuesFile: superset_values.yaml
