apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-processing
# Hay que correr esto antes de empezar para que kustomize encuentre helm
# export helmCommand=/usr/local/bin/helm

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.6.0
    releaseName: airflow-tf-release
    valuesFile: airflow_values.yaml
